// WINDOW
pub const WINDOW_SIZE: f32 = 600.;
pub const MAP_SIZE: f32 = 600.;
pub const CAMERA_DEFAULT_SCALE: f32 = 0.3;
pub const CAMERA_MIN_SCALE: f32 = 0.1;
pub const CAMERA_MAX_SCALE: f32 = 1.;

// PLAYER
pub const PLAYER_SPRITE_SIZE: f32 = 32.;
pub const PLAYER_SPRITE_SCALE: f32 = 0.5;
pub const PLAYER_HITBOX_WIDTH: f32 = PLAYER_SPRITE_SIZE * PLAYER_SPRITE_SCALE;
pub const PLAYER_HITBOX_HEIGHT: f32 = PLAYER_SPRITE_SIZE * PLAYER_SPRITE_SCALE;

// STRUCTURES
pub const TOWER_HEIGHT: f32 = 128.;
pub const TOWER_WIDTH: f32 = 67.;
pub const SANCTUARY_HEIGHT: f32 = 75.;
pub const SANCTUARY_WIDTH: f32 = 96.;