// WINDOW
pub const WINDOW_SIZE: f32 = 600.;

// PLAYER
pub const PLAYER_SPEED: i32 = 1;
pub const PLAYER_SPRITE_SIZE: f32 = 32.;
pub const PLAYER_SPRITE_SCALE: f32 = 0.5;
pub const PLAYER_HITBOX_WIDTH: f32 = PLAYER_SPRITE_SIZE * PLAYER_SPRITE_SCALE;
pub const PLAYER_HITBOX_HEIGHT: f32 = PLAYER_SPRITE_SIZE * PLAYER_SPRITE_SCALE;

// STRUCTURES
pub const TOWER_SIZE: f32 = 100.;
pub const SANCTUARY_SIZE: f32 = 50.;